# -*- Makefile -*-

%+.gasp: %+.tm %.gasp ${TARGET}
	cp  $*.gasp $@
	./${TARGET} commit $< --repo $@

%.gasp : %.elf ${TARGET}
	./${TARGET} init $< --repo $@
	./${TARGET} check --repo $@

check: $(patsubst %.elf, %.gasp, $(wildcard tests/*.elf)) \
       $(patsubst %.tm, %.gasp, $(wildcard tests/*.tm))
